# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  # demands: SpecialSoftware # exists check for SpecialSoftware

steps: 
- script: |
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update
    sudo apt install terraform -y
    terraform version
    echo terrform installed
    sudo apt install awscli -y
    aws --version
    aws s3 ls
    echo aws cli installede
    echo AK Value: $AWS_ACCESS_KEY
    echo SK Value: $AWS_SECRET_KEY
    echo Reg Value: $AWS_DEFAULT_REGION
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY)
    aws configure set aws_secret_access_key $(AWS_SECRET_KEY)
    aws configure set region $(AWS_DEFAULT_REGION)
    terraform init
    terraform fmt
    terraform validate
    terraform plan
  displayName: 'Instsll Terraform and aws cli'
  
  
