# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  # demands: SpecialSoftware # exists check for SpecialSoftware

steps:

- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.3.9'
    terraformDownloadLocation: 'https://releases.hashicorp.com/terraform'
- script: |
    terraform init
    terraform fmt
    terraform validate
    terraform plan
  displayName: 'Run a one-line script'
